name: Lighthouseci

on: 
  [push]

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      # install all dependencies and build storybook
      - name: npm ci
        run: |
          npm ci
          npm run lighthouse-prepare
          npx http-server ./storybook-static > /dev/null 2>&1 &
          npx wait-on http://localhost:8080
      # run the Lighthouse CI tests
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.7.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}